---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mariadb-operator-backup-metrics.fullname" . }}-reader
rules:
  - apiGroups: ["k8s.mariadb.com"]
    resources: ["backups"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mariadb-operator-backup-metrics.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mariadb-operator-backup-metrics.fullname" . }}-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "mariadb-operator-backup-metrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
