name: Build and release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools

      - name: Install OpenSSL
        run: sudo apt-get install --yes libssl-dev

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: x86_64-unknown-linux-musl
          toolchain: stable
          args: "--locked --release"
          strip: true

      - name: Log into Artifactory
        uses: docker/login-action@v1.8.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          logout: true

      - name: Get short SHA of commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build the Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache \
            -t quay.io/duk4s/mariadb-operator-backup-metrics:${SHORT_SHA} \
            -t quay.io/duk4s/mariadb-operator-backup-metrics:latest \
            .

      - name: Push the Docker Image
        run: |
          docker push quay.io/duk4s/mariadb-operator-backup-metrics:${SHORT_SHA}
          docker push quay.io/duk4s/mariadb-operator-backup-metrics:latest

      - name: Package as archive
        shell: bash
        run: |
          cd target/x86_64-unknown-linux-musl/release
          tar czvf ../../../mariadb-operator-backup-metrics-linux-x86_64-musl.tar.gz mariadb-operator-backup-metrics

      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-operator-backup-metrics-Linux-x86_64
          path: "mariadb-operator-backup-metrics-*"

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "mariadb-operator-backup-metrics-*"

